'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Invoices
    Public Property ShipName As String
    Public Property ShipAddress As String
    Public Property ShipCity As String
    Public Property ShipRegion As String
    Public Property ShipPostalCode As String
    Public Property ShipCountry As String
    Public Property CustomerID As String
    Public Property CustomerName As String
    Public Property Address As String
    Public Property City As String
    Public Property Region As String
    Public Property PostalCode As String
    Public Property Country As String
    Public Property Salesperson As String
    Public Property OrderID As Integer
    Public Property OrderDate As Nullable(Of Date)
    Public Property RequiredDate As Nullable(Of Date)
    Public Property ShippedDate As Nullable(Of Date)
    Public Property ShipperName As String
    Public Property ProductID As Integer
    Public Property ProductName As String
    Public Property UnitPrice As Decimal
    Public Property Quantity As Short
    Public Property Discount As Single
    Public Property ExtendedPrice As Nullable(Of Decimal)
    Public Property Freight As Nullable(Of Decimal)

End Class
