'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order_Details_Extended
    Public Property OrderID As Integer
    Public Property ProductID As Integer
    Public Property ProductName As String
    Public Property UnitPrice As Decimal
    Public Property Quantity As Short
    Public Property Discount As Single
    Public Property ExtendedPrice As Nullable(Of Decimal)

End Class
